"""added index

Revision ID: a67472d6c025
Revises: 3ab3b13e4c67
Create Date: 2026-03-08 15:35:20.655618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a67472d6c025'
down_revision: Union[str, Sequence[str], None] = '946d48ae79a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_title', 'posts', ['title'], unique=False)
    op.create_unique_constraint(None, 'posts', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_index('idx_title', table_name='posts')
    # ### end Alembic commands ###
